  [[main]]
  name = "Проекти"
  identifier = "home"
  weight = 100
  url = "/ua/"

  [[main]]
  name = "Галерея"
  weight = 200
  identifier = "portfolio"
  url = "/ua/portfolio/"

  [[main]]
  name = "Про мене"
  weight = 300
  identifier = "about"
  url = "/ua/about/"