title = "Yeva Rizhko"
author = "Yeva Rizhko"
copyright = "Copyright © 2023 Yeva Rizhko"
description = """
Product Designer | UI/UX | Design Systems
"""
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = ["css/custom.css", "css/buttons.css", "css/transition.css"]
# example ["js/custom.js"]
customJs = [] 
mainSections = ["project"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "projects"
# relatedPosts = true
# numberOfRelatedPosts = 3

# displayMode = ""
enableMediumZoom = true
reversepagetitle = false
hidesidebar = false
contentratio = 0.6

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"
# trackerScriptName = "mycustomscriptname.js"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
label = "linkedin.com/in/yevarizhko"
url = "https://www.linkedin.com/in/yevarizhko/"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
label = "yevarizhko@gmail.com"
url = "mailto:yevarizhko@gmail.com"

[mermaid]
# enable = true